BAZAAR : updated maxpdf_frontend app
git-svn-id: svn://ultimatepp.org/upp/trunk@594 f0d560ea-af0d-0410-9eb7-867de7ffcac7

diff --git a/bazaar/maxpdf_frontend/maxpdf b/bazaar/maxpdf_frontend/maxpdf
--- a/bazaar/maxpdf_frontend/maxpdf
+++ b/bazaar/maxpdf_frontend/maxpdf
@@ -34,13 +34,11 @@ PDFGUI=$bindir/maxpdf_frontend
 # Called with no arguments, we list the provided maxpdf backend 
 # (serial devices are irrelevant here).
 if [ $# -eq 0 ]; then
-    for i in faxstat $PDFGUI $MESSAGEBOX ; do 
-        which $i >& /dev/null
-	if [ $? != 0 ]; then
-	    echo "ERROR: can't find MaxPdf program $i" 1>&2
-	    exit 1; 
-	fi
-    done
+    which $PDFGUI >& /dev/null
+    if [ $? != 0 ]; then
+	echo "ERROR: can't find MaxPdf program $i" 1>&2
+	exit 1; 
+    fi
     echo "direct maxpdf:/local \"Unknown\" \"MaxPdf printer\""
     exit 0
 fi
